# GitHub Pages Configuration for Blockchain Toolkit
# Using static HTML files for better control over custom styling

title: "Blockchain Toolkit"
description: "Professional VS Code extension for blockchain development supporting Hardhat, Truffle, Foundry, Solana with advanced debugging and testing capabilities"

# GitHub Pages settings  
url: "https://me-saurabhkohli.github.io"
baseurl: "/blockchain-toolkit"

# Minimal Jekyll configuration for static HTML
plugins: []
markdown: kramdown
highlighter: rouge

# Site metadata
author:
  name: "Saurabh Kohli" 
  email: "me.saurabhkohli@gmail.com"
  github: "me-saurabhkohli"

# SEO settings
lang: en-US

# Include static HTML files
include:
  - "_*.html"
  - "_*.htm"

# Exclude unnecessary files
exclude:
  - README.md
  - LICENSE  
  - node_modules/
  - vendor/
  - Gemfile*
  - "*.md"