# GitHub Pages Configuration for Blockchain Toolkit

# Basic site information
title: "Blockchain Toolkit - VS Code Extension"
description: "Professional blockchain development environment for VS Code supporting Hardhat, Truffle, Foundry, Solana with advanced debugging and testing capabilities"

# URL settings
url: "https://me-saurabhkohli.github.io"
baseurl: "/blockchain-toolkit"

# Build settings - disable Jekyll processing for plain HTML site
plugins: []
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - node_modules/
  - .git/
  - .gitignore