# Blockchain Toolkit GitHub Pages Configuration

title: "Blockchain Toolkit"
description: "Professional VS Code extension for blockchain development supporting Hardhat, Truffle, Foundry, Solana with advanced debugging and testing capabilities"

# GitHub Pages settings
url: "https://me-saurabhkohli.github.io"
baseurl: "/blockchain-toolkit"

# Use GitHub Pages supported theme
theme: jekyll-theme-cayman

# Custom navigation
navigation:
  - title: Features
    url: "#features"
  - title: Frameworks
    url: "#frameworks"
  - title: Documentation
    url: "/docs"
  - title: Examples
    url: "#examples"
  - title: GitHub
    url: "https://github.com/me-saurabhkohli/blockchain-toolkit"

# Site metadata
author:
  name: "Saurabh Kohli"
  email: "saurabh@example.com"
  github: "me-saurabhkohli"

# SEO settings
lang: en-US
logo: "/assets/logo.png"

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - README.md
  - LICENSE
  - node_modules/
  - vendor/

# Custom variables for theme customization
custom:
  primary_color: "#FFF04D"  # Hardhat yellow
  secondary_color: "#1E1823"
  accent_color: "#9CA3AF"