source "https://rubygems.org"
gemspec

gem "github-pages", group: :jekyll_plugins
gem "jekyll-theme-cayman"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
end